name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Jekyll
      uses: helaili/jekyll-action@2.2.0
      with:
        token: ${{ secrets.GITHUB_TOKEN }}
